Develop
tukl-msd/DRAMPower pull request #79
Opened 2020-10-20 08:46 UTC by lulys96

New software architecture, memspecs altered to have JEDEC compliance, DDR3 and DDR4 supported.

2020-11-11 15:43 UTC, myzinsky requested changes
We just did a structural review and have not yet started with checking equations etc.

2020-11-11 15:43 UTC, myzinsky commented on CMakeLists.txt
> +            src/cli/CliHandler.cc
CLI Handler should not be part of the DRAMPower library.

2020-11-11 15:43 UTC, myzinsky commented on CMakeLists.txt
> +add_library(DRAMPower src/cli/drampower.cc
- This drampower.cc should not be part of the library, a library does not have a ```main()```
- Naming should be drampower_cli.cc
- Call the library **DRAMPowerLibrary**

2020-11-11 15:43 UTC, myzinsky commented on CMakeLists.txt
> +            src/TraceParser.cc
Should this not also be part of the CLI?

2020-11-11 15:43 UTC, myzinsky commented on .gitignore
> +CmakeLists.txt.user
It should be CMakeLists.txt.user with capital M

2020-11-11 15:43 UTC, myzinsky commented on CMakeLists.txt.user
> +<?xml version="1.0" encoding="UTF-8"?>
This file should not be in GIT!!

2020-11-11 15:43 UTC, myzinsky commented on DebugFile.txt
> + 	: Parameter ipp2n not found: parsed with zero.
delete

2020-11-11 15:43 UTC, myzinsky commented on Makefile
> -#/*
Please delete this file

2020-11-11 15:43 UTC, myzinsky commented on README.md
> +cmake .
Here we could create a build folder:

```bash
mkdir build
cd build
cmake ../
make
```

And then put the build in the gitignore file :)

2020-11-11 15:43 UTC, myzinsky commented on README.md
> +The format it uses is: ```<timestamp>,<command>,<rank>, <bank>```.
put spaces after comma.

2020-11-11 15:43 UTC, myzinsky commented on README.md
> +./DRAMPowerCli -h
This binary should be called **DRAMPower**

2020-11-11 15:43 UTC, myzinsky commented on README.md
> +	"bankwisespec": {
take care if indention here...

2020-11-11 15:43 UTC, myzinsky commented on README.md
> +"RefreshMode": "1X",
This should be 1, 2, 4 not 1X, 2X, 4X

2020-11-11 15:43 UTC, myzinsky commented on README.md
> +       	"bankwisespec": {
take care on indention!

2020-11-11 15:43 UTC, myzinsky commented on README.md
> +./DRAMPowerCli -m memspecs/MICRON_1Gb_DDR3-1066_8bit_G.json -c traces/commands.trace -r
./DRAMPower is better than DRAMPowerCli

2020-11-11 15:43 UTC, myzinsky commented on README.md
>  The output should be something like this:
I think we can remove this example output. It makes the readme just blowing up...

2020-11-11 15:43 UTC, myzinsky commented on cmake_install.cmake
> +# Install script for directory: /home/luiza/Hiwi/DRAMPower
please remove this file

2020-11-11 15:43 UTC, myzinsky commented on src/MemCommand.cc
> +MemCommand::MemCommand( int64_t timestamp, MemCommand::cmds type,
remove initial whitespace

2020-11-11 15:43 UTC, myzinsky commented on src/MemCommand.h
> +        static std::string type_map[nCommands] = { "ACT",
maybe this map shal be defined near to the enum? Such that we direcetly see what to update if a new command is inserted.

2020-11-11 15:43 UTC, myzinsky commented on src/MemCommand.h
> +    static cmds getTypeFromName(const std::string& name)
Please just keep prototypes in header file and bring the actual implementation to CC files.

2020-11-11 15:43 UTC, myzinsky commented on src/TraceParser.cc
> -/*
Can you keep here the
```c++
/*
*
*
*/
```
styple for the license comment?

2020-11-11 15:43 UTC, myzinsky commented on src/TraceParser.h
> +    TraceParser(){}
why does the trace parser does not have any inputs?

2020-11-11 15:43 UTC, myzinsky commented on src/cli/CliHandler.cc
> + * Copyright (c) 2012-2020, TU Delft
dont change dates of TU Delft and TU Einfhoven, just TUK and IESE :-)

2020-11-11 15:43 UTC, myzinsky commented on src/cli/CliHandler.cc
> +        MemSpecDDR3 memSpecDDR3(jMemSpec,(get_writeToConsole() | get_writeToFile()),
- Why are get_writeToConsole etc relevant for the memspec. This information should go to the library instead.
- We shoud think on the following: 
    - Lets keep the memspec as in DRAMSys as a pure data class
    - Introduce a configuration loader that parses the memspec json and fills the memspec data objects (code of DRAMSys could be reused here)

2020-11-11 15:43 UTC, myzinsky commented on src/cli/CliHandler.cc
> +        MemSpecWideIO memSpecWideIO(jMemSpec,(get_writeToConsole() | get_writeToFile()),
Just a side note, i would format it like this:

```c++
        MemSpecWideIO memSpecWideIO(jMemSpec,
            (get_writeToConsole() | get_writeToFile()),
            get_writeToConsole(),
            get_writeToFile(),
            "DebugFile");
```

2020-11-11 15:43 UTC, myzinsky commented on src/cli/CliHandler.cc
> +    //    else if (memoryType == "WIDEIO2")
This comment shows future work? :-)

2020-11-11 15:43 UTC, myzinsky commented on src/cli/CliHandler.h
> - * Copyright (c) 2012-2014, TU Delft
same as commented below

2020-11-11 15:43 UTC, myzinsky commented on src/common/version.h
> - * Copyright (c) 2012-2014, TU Delft
same

2020-11-11 15:43 UTC, myzinsky commented on src/counters/CountersDDR3.h
> +  void handleRef(    unsigned bank, int64_t timestamp);
we think that all overwritten functions should have a virtual and override specifier.

2020-11-11 15:43 UTC, myzinsky commented on src/dramtypes/DRAMPowerDDR3.cc
> +        if (bank < memSpec.numberOfBanks) {
can you turn this in a switch case?

2020-11-11 15:43 UTC, myzinsky commented on src/dramtypes/DRAMPowerDDR4.cc
> +void DRAMPowerDDR4::bankEnergyCalc(unsigned vdd)
please use directly the right mps as input, such thatt the calling function can pass this as argument: memSpec.memPowerSpec[vdd];

2020-11-11 15:43 UTC, myzinsky commented on src/dramtypes/DRAMPowerIF.cc
>  /*
I think an interface should not have any non-virtual methods, or?

2020-11-11 15:43 UTC, myzinsky commented on valgrind-out.txt
> +==11615== Memcheck, a memory error detector
Please do not push stuff like this...

2020-11-17 13:52 UTC, lulys96 commented on CMakeLists.txt
> +            src/TraceParser.cc
I include the library in the CLI

2022-11-10 14:33 UTC, closed without merging